package com.backend.Enum;

public enum NotificationType {
    JOB_APPLICATION_SUBMITTED,
    APPLICATION_STATUS_CHANGED,
    JOB_APPROVED,
    JOB_REJECTED,
    JOB_MATCHING_SKILLS,
    JOB_DEADLINE_APPROACHING,
    NEW_APPLICATION_RECEIVED
}